rfzeg/virtual_racetracks_collection

- launch/race-track-JS1w1UOQ.launch
It has been created a new race track with hearth shape
> New race track hearth shape made

- launch/race-track-EMyXMONO.launch
Following the instruction of the coursework
> Add a new race track (EMyXMONO)

- launch/race-track-JZ5wbOXS.launch
> added hourglass track

- launch/race-track-sdfa4543.launch
Octogonal race track as part of the Construct's Git and Github Course
> Add Octagonal Race Track

- launch/race-track-Rh8AxCEF.launch
Hi,
I added a new launch file in the repository, which is one part of course "Git and GitHub Course".
> add race-track-Rh8AxCEF.launch

- launch/race-track-aoNofgpb.launch
I have just inserted two points between "p10" and "p11" as follows.
<arg name="p10" value="{x: 7.0, y: 8.0, z: 0.0}"/>
<arg name="p11" value="{x: 7.0, y: 9.0, z: 0.0}"/>
<arg name="p12" value="{x: 4.0, y: 9.0, z: 0.0}"/>
<arg name="p13" value="{x: 4.0, y: 8.0, z: 0.0}"/>
That' all I did. I have tried 'git push' and 'pull request' exercises.
> Add my race track to launch directory (2 points added)

- launch/race-track-aBLDMsMO.launch
Added new file: `race-track-aBLDMsMO.launch`.
> Added new race_track launch file

- launch/race-track-J170AF91.launch
This Pull Request holds new launch file called "race-track-J170AF91" 
this track has new shape for testing the robot.
Branch name according to guidelines.
> New Track race-track-J170AF91

- launch/race-track-rXa14Fi9.launch
Large Dolphin inspired track. Robot starts on track starting point.
> Add RaceTrack rXa14Fi9 ("Huge Dolphin")

- launch/race-track-26NKzM0j.launch
> Created a new race track

- launch/race-track-LJRIby8x.launch
> Adding race-track-LJRIby8x.launch (F race track)

- launch/race-track-7ei5gMie.launch
> Add a hexagonal racetrack

- launch/race-track-SJgduWcC.launch
I have created a new race-track named 'race-track-SJgduWcC'.
> new ractrack added race-track

- launch/race-track-SWPpa08u.launch
> Pull Request #33 - customization of a track

- launch/race-track-hJm8k6rW.launch
This is a heart shaped race track with interesting turns. The race track reminds us to spread love and kindness across the world!
> Added race-track-hJm8k6rW

- launch/race-track-jntYkSKQ.launch
A basic figure 8 shaped race track with a ramp
> Basic figure-8 racetrack

- launch/race-track-VE6fkDj4.launch
Added new race track VE6fkDj4y, shown in the picture below:
> Add race track VE6fkDj4y

- launch/race-track-mWYhJorn.launch
Created a new launch file called "race-track-mWYhJorn.launch" with a custom racetrack. 
The racetrack has 13 points and describes an "infinit simbol" path. I also changed the color of the track to light green ( value="color: {a: 1.0, b: 0.25, g: 0.5, r: 0.25}" )
> Added a new launchfile called race-track-mWYhJorn.launch

- launch/race-track-J2DzhxfK.launch
> Add the simplest track ever

- launch/race-track-8cZhHQ2J.launch
**Add new racetrack race-track-8cZhHQ2J:** Add New Racetrack for Arviz
**Description:**
Hello,
I've created a new racetrack launch file for rviz, regarding the "Unit 5:  Course Project" of the Git and GitHub course.
Thank you for considering my contribution!
Sincerely,
Alex Alcón
> Add new racetrack: race-track-8cZhHQ2J
